### ISSUE TITLE
hydra-eval-jobs reporting error: unexpected EOF reading a line

### ISSUE THREAD

**Issue by peeech** [Holo-Host/bugs-n-issues#39] opened 2022-03-16 11:22 UTC
After merge of https://github.com/Holo-Host/holo-nixpkgs/pull/1184 Hydra is reporting Evaluation Error:
```
hydra-eval-jobs returned exit code 1:
error: unexpected EOF reading a line
```
see here: https://hydra.holo.host/jobset/holo-nixpkgs/develop#tabs-errors

---

The current goal of this ticket is to have Hydra raise a more relevant error message indicating that the process was killed and by what signal.

**Comment by firestack** [comment] 2022-03-22 14:25
I've been able to correlate machine metrics and machine logs by hand and have determined that `hydra-eval-jobs` was being OOM-Killed due to the memory consumption addressed in https://github.com/Holo-Host/holo-nixpkgs/pull/1189 

<details>
<summary>
Correlated Logs
</summary>

---
### Machine
[hydra-dev.holo.host](hydra-dev.holo.host)

### Log Retrieval
```
journalctl -u hydra-evaluator -S '2022-03-16 00:22:00' -g 'exit code 1'
```
### First Instance of OOM Affecting Jobs
[raintank snapshot 1/20220316](https://snapshots-origin.grafana.net/dashboard/snapshot/tsS1sNy3hTr3VtqG84BQtThr837YpgPf?orgId=2)
![image](https://user-images.githubusercontent.com/6913198/159500742-9cc243f0-806e-458e-ba38-602f775a64b1.png)

```
Wed 2022-03-16 10:36:45 UTC hydra hydra-evaluator[1689125]: hydra-eval-jobs returned exit code 1:
Wed 2022-03-16 10:36:45 UTC hydra hydra-evaluator[1689100]: evaluation of jobset ‘holo-nixpkgs:develop (jobset#265)’ failed with exit code 1
Wed 2022-03-16 10:41:33 UTC hydra hydra-evaluator[1944594]: hydra-eval-jobs returned exit code 1:
Wed 2022-03-16 10:41:33 UTC hydra hydra-evaluator[1944588]: evaluation of jobset ‘holo-nixpkgs:pr-872 (jobset#552)’ failed with exit code 1
Wed 2022-03-16 10:56:19 UTC hydra hydra-evaluator[3174435]: hydra-eval-jobs returned exit code 1:
Wed 2022-03-16 10:56:19 UTC hydra hydra-evaluator[3174418]: evaluation of jobset ‘holo-nixpkgs:develop (jobset#265)’ failed with exit code 1
Wed 2022-03-16 11:00:35 UTC hydra hydra-evaluator[3369622]: hydra-eval-jobs returned exit code 1:
Wed 2022-03-16 11:00:35 UTC hydra hydra-evaluator[3369616]: evaluation of jobset ‘holo-nixpkgs:pr-1127 (jobset#561)’ failed with exit code 1
Wed 2022-03-16 11:05:33 UTC hydra hydra-evaluator[3703296]: hydra-eval-jobs returned exit code 1:

... < Continues repeating until >

Thu 2022-03-17 20:46:05 UTC hydra hydra-evaluator[2979038]: hydra-eval-jobs returned exit code 1:
Thu 2022-03-17 20:46:05 UTC hydra hydra-evaluator[2979030]: evaluation of jobset ‘holo-nixpkgs:develop (jobset#265)’ failed with exit code 1
Thu 2022-03-17 20:49:08 UTC hydra hydra-evaluator[3196350]: hydra-eval-jobs returned exit code 1:
Thu 2022-03-17 20:49:09 UTC hydra hydra-evaluator[3196342]: evaluation of jobset ‘holo-nixpkgs:1127 (jobset#505)’ failed with exit code 1
Thu 2022-03-17 20:52:52 UTC hydra hydra-evaluator[3412987]: hydra-eval-jobs returned exit code 1:
Thu 2022-03-17 20:52:52 UTC hydra hydra-evaluator[3412980]: evaluation of jobset ‘holo-nixpkgs:1188 (jobset#566)’ failed with exit code 1
Thu 2022-03-17 20:56:28 UTC hydra hydra-evaluator[3619827]: hydra-eval-jobs returned exit code 1:
Thu 2022-03-17 20:56:28 UTC hydra hydra-evaluator[3619772]: evaluation of jobset ‘holo-nixpkgs:develop (jobset#265)’ failed with exit code 1
Thu 2022-03-17 21:00:12 UTC hydra hydra-evaluator[3782245]: hydra-eval-jobs returned exit code 1:
Thu 2022-03-17 21:00:12 UTC hydra hydra-evaluator[3782237]: evaluation of jobset ‘holo-nixpkgs:1127 (jobset#505)’ failed with exit code 1

```

---

### Second Instance of OOM Affecting Jobs
[raintank snapshot 2/20220320](https://snapshots-origin.grafana.net/dashboard/snapshot/DEqro60cXWXoCGeU6M7LLNfMZyp4a3zG?orgId=2)
![image](https://user-images.githubusercontent.com/6913198/159500990-43da1fc4-db10-4f71-b7df-a7d9d469a58a.png)

```
Mon 2022-03-21 00:16:18 UTC hydra hydra-evaluator[4138428]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:16:35 UTC hydra hydra-evaluator[4138428]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:16:51 UTC hydra hydra-evaluator[4138428]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:17:11 UTC hydra hydra-evaluator[4140965]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:17:28 UTC hydra hydra-evaluator[4140965]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:17:45 UTC hydra hydra-evaluator[4140965]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:18:02 UTC hydra hydra-evaluator[4140965]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:18:19 UTC hydra hydra-evaluator[4140965]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:18:35 UTC hydra hydra-evaluator[4140965]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:18:52 UTC hydra hydra-evaluator[4140965]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:19:09 UTC hydra hydra-evaluator[4140965]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:19:25 UTC hydra hydra-evaluator[4140965]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:19:42 UTC hydra hydra-evaluator[4140965]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:19:59 UTC hydra hydra-evaluator[4140965]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:20:17 UTC hydra hydra-evaluator[4140965]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:20:33 UTC hydra hydra-evaluator[4140965]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:20:49 UTC hydra hydra-evaluator[4140965]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:21:06 UTC hydra hydra-evaluator[4140965]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:21:25 UTC hydra hydra-evaluator[4140965]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:21:41 UTC hydra hydra-evaluator[4140965]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:21:58 UTC hydra hydra-evaluator[4140965]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:22:14 UTC hydra hydra-evaluator[4140965]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:22:30 UTC hydra hydra-evaluator[4140965]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:22:46 UTC hydra hydra-evaluator[4140965]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:23:02 UTC hydra hydra-evaluator[4140965]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:23:19 UTC hydra hydra-evaluator[4140965]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:23:38 UTC hydra hydra-evaluator[4140965]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:23:55 UTC hydra hydra-evaluator[4140965]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:24:12 UTC hydra hydra-evaluator[4140965]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:24:28 UTC hydra hydra-evaluator[4140965]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1
Mon 2022-03-21 00:24:44 UTC hydra hydra-evaluator[4140965]: evaluation of jobset ‘holo-nixpkgs:.jobsets (jobset#264)’ failed with exit code 1

--- Reboot Occurred ---

-- Boot 57dc5dc20efb4c93afa4dc958c332a94 --
Mon 2022-03-21 00:29:03 UTC hydra hydra-evaluator[147844]: hydra-eval-jobs returned exit code 1:
Mon 2022-03-21 00:29:04 UTC hydra hydra-evaluator[147838]: evaluation of jobset ‘holo-nixpkgs:1127 (jobset#505)’ failed with exit code 1
Mon 2022-03-21 00:32:58 UTC hydra hydra-evaluator[378040]: hydra-eval-jobs returned exit code 1:
Mon 2022-03-21 00:32:58 UTC hydra hydra-evaluator[378034]: evaluation of jobset ‘holo-nixpkgs:1185 (jobset#564)’ failed with exit code 1
```

---

`hydra-evaluator.service` seems to at least be aware that `hydra-eval-jobs` was killed by `OOM killer`
```
Wed 2022-03-16 10:38:40 UTC hydra systemd[1]: hydra-evaluator.service: A process of this unit has been killed by the OOM killer.
Wed 2022-03-16 10:38:40 UTC hydra systemd[1]: hydra-evaluator.service: Main process exited, code=exited, status=1/FAILURE
Wed 2022-03-16 10:38:57 UTC hydra systemd[1]: hydra-evaluator.service: Failed with result 'oom-kill'.
Wed 2022-03-16 10:38:57 UTC hydra systemd[1]: hydra-evaluator.service: Consumed 5min 10.160s CPU time, received 28.9K IP traffic, sent 14.1K IP traffic.
Wed 2022-03-16 10:38:57 UTC hydra systemd[1]: hydra-evaluator.service: Scheduled restart job, restart counter is at 3.
Wed 2022-03-16 10:38:57 UTC hydra systemd[1]: Stopped hydra-evaluator.service.
Wed 2022-03-16 10:38:57 UTC hydra systemd[1]: hydra-evaluator.service: Consumed 5min 10.160s CPU time, received 28.9K IP traffic, sent 14.1K IP traffic.
Wed 2022-03-16 10:38:57 UTC hydra systemd[1]: Started hydra-evaluator.service.

---

Mon 2022-03-21 00:29:37 UTC hydra systemd[1]: hydra-evaluator.service: A process of this unit has been killed by the OOM killer.
Mon 2022-03-21 00:29:37 UTC hydra systemd[1]: hydra-evaluator.service: Main process exited, code=exited, status=1/FAILURE
Mon 2022-03-21 00:30:53 UTC hydra systemd[1]: hydra-evaluator.service: Failed with result 'oom-kill'.
Mon 2022-03-21 00:30:53 UTC hydra systemd[1]: hydra-evaluator.service: Consumed 4min 13.612s CPU time, read 417.0M from disk, written 4.0K to disk, received 20>
Mon 2022-03-21 00:30:53 UTC hydra systemd[1]: hydra-evaluator.service: Scheduled restart job, restart counter is at 2.
Mon 2022-03-21 00:30:53 UTC hydra systemd[1]: Stopped hydra-evaluator.service.
Mon 2022-03-21 00:30:53 UTC hydra systemd[1]: hydra-evaluator.service: Consumed 4min 13.612s CPU time, read 417.0M from disk, written 4.0K to disk, received 20>
Mon 2022-03-21 00:30:53 UTC hydra systemd[1]: Started hydra-evaluator.service.
```
---
</details>

#33 will help with surfacing this kind of correlation sooner, but the error returned by hydra's web UI is lacking of context from what actually happened in the backend. Hydra does seem to try to restart the job before giving up ( as shown by this job completing after being attempted multiple times during memory issues https://hydra-dev.holo.host/eval/2304093 of 2022-03-21 ) It might be best if we could adjust hydra to return a more verbose answer to what caused `hydra-eval-jobs` to report the following 
```
hydra-eval-jobs returned exit code 1:
error: unexpected EOF reading a line
```

**Comment by grahamc** [comment] 2022-03-22 16:12
Hey @peeech we think this is solved by the same PR (1189) which solved #40. These EOF errors come when hydra-eval-jobs gets killed. In other words, this is basically the same issue but a secondary symptom. I think that means we can close this.

**Comment by grahamc** [comment] 2022-03-22 16:14
As @firestack suggested, though, we might want to use this ticket to improve the error reporting to say it did get killed. What do you think about that?

**Comment by peeech** [comment] 2022-03-23 11:41
In fact PR (1189) seems to be fixing #39 as well. We can close this ticket but I am happy to help in improving error handling of Hydra as well. Please let me know which way do you want to go (maybe both?) and what kind of action it requires on my end.

**Comment by firestack** [comment] 2022-04-25 19:42
Hi @peeech,

Wanted to update you that we've reproduced and addressed this error text in a local development branch of hydra. I'm currently, as time permits, drafting a PR to get this upstreamed. We should expect to see this wrapped up soon.

**Comment by peeech** [comment] 2022-04-26 08:25
I am very glad to hear that. Can you post a link to an upstream PR once it's ready @firestack ?

**Comment by firestack** [comment] 2022-04-29 16:01
@peeech I've just opened it! link here https://github.com/NixOS/hydra/pull/1203

**Comment by firestack** [comment] 2022-05-02 19:51
aaaaaand it's merged 🎉

**Comment by peeech** [comment] 2022-05-04 19:20
First we need to bump Hydra to revision that contains #1203, don't we?

**Comment by firestack** [comment] 2022-05-04 20:39
Yeah! Should we do that as a part of this ticket or open another issue to maybe set up auto updates via PR like the nixpkgs updater?

**Comment by peeech** [comment] 2022-05-04 20:41
I would do it as a part of this ticket

**Comment by firestack** [comment] 2022-05-04 20:52
There we go!

**Closed** 2022-05-05 21:07 UTC
Labels: bug, priority
