### ISSUE TITLE
Configure log aggregation

### ISSUE THREAD

**Issue by grahamc** [Holo-Host/bugs-n-issues#33] opened 2022-03-01 15:14 UTC
- [x] Recommend a third party log aggregation service
- [x] Prototype the implementation on Hydra
- [ ] Roll out the log aggregation to all of the devnet machines, by merging to develop

The log messages should be tagged by "main" net or "dev" net.

In support of #11.

**Comment by alastairong** [comment] 2022-03-02 13:32
@grahamc @peeech FYI found out that we have a papertrail account so that would be preferred. We can provide you with access to that. Any issues?

**Comment by firestack** [comment] 2022-03-03 18:36
We'll look into papertrail and get back to you @alastairong.

**Comment by firestack** [comment] 2022-03-10 18:39
I've taken some time to review `papertrail` as well as some other logging solutions, specifically with respect to each service's handling of structured logging and compatibility with `journald`.

I'd like to suggest that you consider using/switching to Grafana Cloud, for hosted log aggregation and storage, because they offer structured logging via JSON.

Structured logging provides a better way to add and query metadata from log entries, usually taking the place of regular expressions searching an entire log string. Storing logs using json should make retrieving and interacting with log entries easier than say a counterpart which uses regex to parse field info from syslog entries.

We can also use papertrail If you would prefer to continue using them. Papertrail does seem to prefer syslog over structured logging with json.

**Comment by grahamc** [comment] 2022-03-16 13:40
@peeech and I discussed this on our call today. He's planning on looking in to if Papertrail is used / integrated into their workflow. If not, he's happy to try loki / Grafana Cloud. He'll get back to us this week.

**Comment by alastairong** [comment] 2022-03-17 09:46
@peeech @grahamc Confirmed that we're not particularly invested in papertrail. Go ahead with Grafana.

**Comment by firestack** [comment] 2022-03-24 13:40
To move forward we need to do a few things

- [ ] Holo.host Creates a Grafana Cloud Account that Holo.host owns the credentials and information of
   - This process will automatically ask you to create a named Grafana Cloud "Stack" during the account creation process
- Within the stack management panel on `https://grafana.com/orgs/<stackname>/members` 
   - [ ] Provide users who need access to Logs and Metrics access to Grafana 
      - This can be done by an admin individually inviting users to the grafana stack with the `Editors` or `Viewers` role
   - (Optional) [Configure Single Sign On within `https://grafana.com/orgs/<stackname>` in the `Security/Advanced Auth` section](https://grafana.com/docs/grafana-cloud/authentication-and-permissions/authorization/)
   - [ ] Invite users who need the ability to create Grafana Cloud API keys
      - Invite users with the `Admins` role

**Comment by firestack** [comment] 2022-03-31 17:48
We've got hydra uploading logs from `hydra.holo.host` to grafana cloud loki! The results of the test can be seen here https://holo.grafana.net/goto/ZxTPD-s7z?orgId=1

cc: @grahamc @peeech

**Comment by grahamc** [comment] 2022-03-31 18:52
One thing @peeech is you'll need to coordinate distributing the API secret to each machine. We placed it by hand on hydra, but it should be integrated into your standard process for deploying.

**Comment by peeech** [comment] 2022-04-01 08:54
@alastairong I invited you to Grafana

**Comment by peeech** [comment] 2022-04-01 09:38
Progress blocked by https://github.com/Holo-Host/bugs-n-issues/issues/42

**Comment by grahamc** [comment] 2022-04-05 16:05
Should be unblocked.

**Comment by peeech** [comment] 2022-04-06 08:28
Successful roll-out to all devned machines requires including `logging.nix` in:
- [ ] `holochain-proxy` profile
- [ ] `match-server` profile
- [ ] `membrane-proof-server` profile
- [ ] `router-gateway` profile

**Comment by peeech** [comment] 2022-04-06 08:54
^ addressed in https://github.com/Holo-Host/holo-nixpkgs/pull/1220

**Comment by peeech** [comment] 2022-04-07 02:56
Yes, thank you. I am waiting for #1220 to be merged before I can continue.

BTW I have noticed that `/var/lib/promtail-auth/api-token` has `-rw-------` permissions. I was thinking that it should be `-r--------` and your code examples confirm that this is a case. Lemme know if there's a any reason for that.

**Comment by peeech** [comment] 2022-04-07 11:07
I can confirm in e.g. [this query](https://holo.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-holo-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bjob%3D%5C%22systemd-journal%5C%22,%20unit%3D%5C%22sshd.service%5C%22,%20nodename%3D%5C%22devnet-router-gateway%5C%22%7D%20%5Cn%7C%20json%20%5Cn%7C%20line_format%20%5C%22%7B%7B.nodename%7D%7D.%7B%7B.holoNetwork%7D%7D%5C%5Ct%7B%7B.unit%7D%7D%5C%5Cn%7B%7B.MESSAGE%7D%7D%5C%22%20%7C%3D%20%5C%22peeech%5C%22%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D%7D,%7B%22refId%22:%22B%22,%22expr%22:%22sum%20by%20(holoNetwork,nodename)%20(rate(%7Bjob%3D%5C%22systemd-journal%5C%22%7D%5B$__interval%5D))%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D) that logging is in fact working. For now it is activated on hydra, devnet-router-gateway and devnet-holochain-proxy.

**Comment by peeech** [comment] 2022-04-07 11:07
Thanks everybody for great work!

**Closed by peeech** 2022-04-07 11:07 UTC
Labels: priority
